services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: super_secret_jwt
      NEXT_SERVER_API_URL: http://host.docker.internal:8000/api
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
