services:
  express-api:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
